[project]
name = "silaba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-texttospeech>=2.26.0",
    "httpx>=0.27.2",
    "pyglet>=2.0.17",
]
